[package]
name = "advent-of-code-2023"
version = "0.1.69"
edition = "2021"

[[bin]]
name = "d01"
path = "src/d01/main.rs"

[[bin]]
name = "d02"
path = "src/d02/main.rs"

[dependencies]
itertools = "0.12.0"
nom = "7.1.3"
